### ISSUE TITLE
Exception bricks whole cart and checkout.

### ISSUE THREAD

**Issue by toonvd** [MultiSafepay/shopware#6]
MultiSafePay API being down bricks cart and checkout from webshops also using other payment methods.

https://github.com/MultiSafepay/shopware/blob/6a897dbc78b54b64d1b6813e9622610e26dab51d/Components/API/MspClient.php#L135

https://github.com/MultiSafepay/shopware/blob/6a897dbc78b54b64d1b6813e9622610e26dab51d/Components/API/Object/Core.php#L104

These should not throw an exception but write something to the logs.

Also, the timeout is way too large. 5 seconds would be more appropriate.

https://github.com/MultiSafepay/shopware/blob/6a897dbc78b54b64d1b6813e9622610e26dab51d/Components/API/MspClient.php#L121

**Comment by Mike-MultiSafepay** [comment]
Hi @toonvd 

We are currently implementing our PHP-SDK into the Shopware plugin. This should fix the long CURL timeout timer.

We will also look into the exceptions that the payment page give when the MultiSafepay servers cannot be reached. and create a fallback for iDEAL bank list when this happens.

I will keep you updated on this.

**Comment by Mike-MultiSafepay** [comment]
Hi @toonvd 

We just released version 2.11.1 which includes the new PHP-SDK instead of using the curl calls. which includes a better logger of the API calls. and should not take 2 minutes for a timeout error to occur.

If the issue is still not solved don't hesitate to reopen this ticket
